--------------------------------------------------------
--  파일이 생성됨 - 목요일-9월-15-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOBBYMEMBERT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."HOBBYMEMBERT" 
   (	"H_UID" VARCHAR2(15 BYTE), 
	"H_PWD" VARCHAR2(15 BYTE), 
	"H_NAME" VARCHAR2(20 BYTE), 
	"H_EMAIL" VARCHAR2(50 BYTE), 
	"H_REGDATE" DATE, 
	"H_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.HOBBYMEMBERT
SET DEFINE OFF;
Insert into SCOTT.HOBBYMEMBERT (H_UID,H_PWD,H_NAME,H_EMAIL,H_REGDATE,H_ADDRESS) values ('jej2854','1234','전은주','jej2854@naver.com',to_date('22/09/15','RR/MM/DD'),'부산시 부산진구');
Insert into SCOTT.HOBBYMEMBERT (H_UID,H_PWD,H_NAME,H_EMAIL,H_REGDATE,H_ADDRESS) values ('qqqq','qqqq','Q','Q@naver.com',to_date('22/09/15','RR/MM/DD'),'부산시 부산진구');
--------------------------------------------------------
--  DDL for Index SYS_C007159
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007159" ON "SCOTT"."HOBBYMEMBERT" ("H_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HOBBYMEMBERT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."HOBBYMEMBERT" ADD PRIMARY KEY ("H_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
