DESC SEMI_USERTABLE;
SELECT * FROM SEMI_USERTABLE;

SELECT * FROM SEMI_ADMINTABLE;
DESC SEMI_ADMINTABLE;

SELECT * FROM SEMI_JOINTABLE;
DESC SEMI_JOINTABLE;

SELECT * FROM SEMI_BOARDTABLE;
DESC SEMI_BOARDTABLE;

SELECT * FROM SEMI_NOTICETABLE;
DESC SEMI_NOTICETABLE;

SELECT * FROM  SEMI_BOARDCOMMENT ORDER BY bc_date;
DESC SEMI_BOARDCOMMENT;

SELECT * FROM  SEMI_JOINCOMMENT ORDER BY jc_date;
DESC SEMI_JOINCOMMENT;