-- FK로 DROP은 거꾸로 실행
DROP TABLE SEMI_JOINCOMMENT;
DROP TABLE SEMI_BOARDCOMMENT;
DROP TABLE SEMI_NOTICETABLE;
DROP TABLE SEMI_BOARDTABLE;
DROP TABLE SEMI_JOINTABLE;
DROP TABLE SEMI_ADMINTABLE;
DROP TABLE SEMI_USERTABLE;